# Generated by Django 5.1.5 on 2025-01-19 23:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='プロジェクト名')),
                ('location', models.CharField(max_length=200, verbose_name='現場所在地')),
                ('start_date', models.DateField(verbose_name='着工日')),
                ('end_date', models.DateField(verbose_name='竣工予定日')),
                ('description', models.TextField(blank=True, verbose_name='工事概要')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='現場監督')),
            ],
            options={
                'verbose_name': '工事プロジェクト',
                'verbose_name_plural': '工事プロジェクト',
            },
        ),
    ]
