# Generated by Django 5.1.5 on 2025-01-25 12:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
            ],
            options={
                'verbose_name': '資材カテゴリ',
                'verbose_name_plural': '資材カテゴリ',
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='資材名')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='資材コード')),
                ('specification', models.CharField(blank=True, max_length=200, verbose_name='規格')),
                ('unit', models.CharField(max_length=50, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='単価')),
                ('current_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='現在の在庫数')),
                ('minimum_stock', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='最小在庫数')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='materials', to='materials.materialcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '資材',
                'verbose_name_plural': '資材',
                'ordering': ['category', 'code'],
            },
        ),
        migrations.CreateModel(
            name='MaterialTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('in', '入庫'), ('out', '出庫')], max_length=3, verbose_name='取引種類')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='数量')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='取引単価')),
                ('transaction_date', models.DateField(verbose_name='取引日')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='発注番号')),
                ('delivery_number', models.CharField(blank=True, max_length=100, verbose_name='納品番号')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='materials.material', verbose_name='資材')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_transactions', to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '資材取引',
                'verbose_name_plural': '資材取引',
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
    ]
