# Generated by Django 5.1.5 on 2025-01-25 12:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CostCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='カテゴリ名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '原価カテゴリ',
                'verbose_name_plural': '原価カテゴリ',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Cost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100, verbose_name='項目名')),
                ('planned_amount', models.DecimalField(decimal_places=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)], verbose_name='予算金額')),
                ('actual_amount', models.DecimalField(blank=True, decimal_places=0, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='実績金額')),
                ('payment_status', models.CharField(choices=[('unpaid', '未払い'), ('partially_paid', '一部支払済'), ('paid', '支払済')], default='unpaid', max_length=20, verbose_name='支払状況')),
                ('payment_date', models.DateField(blank=True, null=True, verbose_name='支払日')),
                ('invoice_number', models.CharField(blank=True, max_length=50, verbose_name='請求書番号')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='costs', to='projects.project', verbose_name='プロジェクト')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='costs', to='costs.costcategory', verbose_name='カテゴリ')),
            ],
            options={
                'verbose_name': '原価',
                'verbose_name_plural': '原価',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
    ]
