# Generated by Django 5.1.5 on 2025-01-25 12:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=200, verbose_name='作業項目')),
                ('planned_start_date', models.DateField(verbose_name='開始予定日')),
                ('planned_end_date', models.DateField(verbose_name='終了予定日')),
                ('actual_start_date', models.DateField(blank=True, null=True, verbose_name='実際の開始日')),
                ('actual_end_date', models.DateField(blank=True, null=True, verbose_name='実際の終了日')),
                ('status', models.CharField(choices=[('not_started', '未着手'), ('in_progress', '進行中'), ('completed', '完了'), ('delayed', '遅延')], default='not_started', max_length=20, verbose_name='状況')),
                ('progress', models.IntegerField(default=0, verbose_name='進捗率')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='担当者')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedules', to='projects.project', verbose_name='プロジェクト')),
            ],
            options={
                'verbose_name': '工程',
                'verbose_name_plural': '工程',
                'ordering': ['planned_start_date', 'planned_end_date'],
            },
        ),
    ]
